### ISSUE TITLE
Adding Unit Test Case for Signup Page

### ISSUE THREAD

**Issue by Jagroop2000** [KartuzGupta/Chat-App#11]
Hi @KartuzGupta  !!
I have added a unit test case for the Signup Page.
Please accept this under **CODEPEAK 2022**

**Comment by Jagroop2000** [comment]
Hi @KartuzGupta , Also Please mentioned points here  like this. It would be really appreciating

![Screenshot from 2022-12-15 20-17-54](https://user-images.githubusercontent.com/99062463/207891020-a9d21b7b-74ca-4825-9d96-4de5a21f76df.png)

**Comment by KartuzGupta** [comment]
> Hi @KartuzGupta , Also Please mentioned points here like this. It would be really appreciating
> 
> ![Screenshot from 2022-12-15 20-17-54](https://user-images.githubusercontent.com/99062463/207891020-a9d21b7b-74ca-4825-9d96-4de5a21f76df.png)

points have been awarded
