### ISSUE TITLE
Unit Test for Chat-App

### ISSUE THREAD

**Issue by Jagroop2000** [KartuzGupta/Chat-App#7]
Hi there !!

I want to add unit tests for the Chap-App. 
I am using Jest which is auto-installed in the package-lock.json file.

Please Allow me this under CODEPEAK
Hoping to hear from you soon!!

**Comment by KartuzGupta** [comment]
> Hi there !!
> 
> I want to add unit tests for the Chap-App. I am using Jest which is auto-installed in the package-lock.json file.
> 
> Please Allow me this under CODEPEAK Hoping to hear from you soon!!

Okay go adead with your idea

**Comment by Jagroop2000** [comment]
Hi @KartuzGupta !!

Please Add Level and CODEPEAK Label for this.

**Comment by Jagroop2000** [comment]
Hi @KartuzGupta, Please merge my pull request so that I will work on further components.

**Comment by Jagroop2000** [comment]
Hi @KartuzGupta !!
Can you please add  points to this issue as well  like this :
![Screenshot from 2022-12-15 20-17-54](https://user-images.githubusercontent.com/99062463/208300746-5f21563c-715b-40bb-9fbb-488e4eb5b7d4.png)

**Comment by KartuzGupta** [comment]
> Hi @KartuzGupta !! Can you please add points to this issue as well like this : ![Screenshot from 2022-12-15 20-17-54](https://user-images.githubusercontent.com/99062463/208300746-5f21563c-715b-40bb-9fbb-488e4eb5b7d4.png)

tags have been added to your PR
